language: objective-c
osx_image: xcode8
notifications:
  email: false

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=demo/demo.xcworkspace
  - IOS_SCHEME="demo"
  - IOS_SDK=iphonesimulator10.0
  
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 6S" SCHEME="$IOS_SCHEME" SDK="$IOS_SDK" RUN_TESTS="YES"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build in Debug and Run Tests
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
